Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Templates/Controllers/PreviewController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Display;
using OrchardCore.ContentPreview;
using OrchardCore.DisplayManagement.ModelBinding;
using OrchardCore.Environment.Shell;
using OrchardCore.Settings;
using OrchardCore.Templates.ViewModels;

namespace OrchardCore.Templates.Controllers
{
    public class PreviewController : Controller
    {
        private readonly IContentManager _contentManager;
        private readonly IContentHandleManager _contentHandleManager;
        private readonly IContentItemDisplayManager _contentItemDisplayManager;
        private readonly IAuthorizationService _authorizationService;
        private readonly ISiteService _siteService;
        private readonly IUpdateModelAccessor _updateModelAccessor;
        private readonly string _homeUrl;

        public PreviewController(
            IContentManager contentManager,
            IContentHandleManager contentHandleManager,
            IContentItemDisplayManager contentItemDisplayManager,
            IAuthorizationService authorizationService,
            ISiteService siteService,
            ShellSettings shellSettings,
            IUpdateModelAccessor updateModelAccessor)
        {
            _contentManager = contentManager;
            _contentHandleManager = contentHandleManager;
            _contentItemDisplayManager = contentItemDisplayManager;
            _authorizationService = authorizationService;
            _siteService = siteService;
            _updateModelAccessor = updateModelAccessor;
            _homeUrl = ('/' + (shellSettings.RequestUrlPrefix ?? string.Empty)).TrimEnd('/') + '/';
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Render()
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageTemplates))
            {
                return this.ChallengeOrForbid();
            }

            // Mark request as a `Preview` request so that drivers / handlers or underlying services can be aware of an active preview mode.
            HttpContext.Features.Set(new ContentPreviewFeature());

            var name = Request.Form["Name"];
            var content = Request.Form["Content"];

            if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(content))
            {
                HttpContext.Items["OrchardCore.PreviewTemplate"] = new TemplateViewModel { Name = name, Content = content };
            }

            var handle = Request.Form["Handle"].ToString();

            string contentItemId;

            if (string.IsNullOrEmpty(handle) || handle == _homeUrl)
            {
                var homeRoute = (await _siteService.GetSiteSettingsAsync()).HomeRoute;
                contentItemId = homeRoute["contentItemId"]?.ToString();
            }
            else
            {
                var index = handle.IndexOf(_homeUrl, StringComparison.Ordinal);
                handle = (index < 0) ? handle : handle.Substring(_homeUrl.Length);
                contentItemId = await _contentHandleManager.GetContentItemIdAsync("slug:" + handle);
            }

            if (string.IsNullOrEmpty(contentItemId))
            {
                return NotFound();
            }

            var contentItem = await _contentManager.GetAsync(contentItemId, VersionOptions.Published);

            if (contentItem == null)
            {
                return NotFound();
            }

            var model = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, _updateModelAccessor.ModelUpdater, "Detail");

            return View(model);
        }
    }
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Templates/Views/Preview/Index.cshtml
@{
    Layout = "_Layout";
    Title.AddSegment(T["Template Preview"]);
}

<script asp-name="js-cookie" at="Foot"></script>

<iframe id="iframe" style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden;z-index:999990;">
    Your browser doesn't support iframes
</iframe>

<div id="notConnectedWarning" class="alert alert-info alert-dismissible fade show collapse" role="alert" style="position:fixed; height:60px; top:10px; right:40px; display:none; z-index:999999;">
    <button type="button" id="close-warning" class="btn-close" aria-label="Close" style="position: relative; padding: 0 0 0 1rem; margin-top: -0.2rem;"></button>
    <span>@T["Preview Disconnected"] </span>
</div>

<div id="serverErrorWarning" class="alert alert-warning alert-dismissible fade show" role="alert" style="position:fixed; top:10px; right:40px; display:none; z-index:999999;">
    <button type="button" id="close-server-warning" class="btn-close" aria-label="Close" style="position: relative; padding: 0 0 0 1rem; margin-top: -0.2rem;"></button>
    <p>@T["Preview Error"] </p>
    <ul></ul>
</div>

<div id="indexPreviewUrl" style="display:none" data-value="@Url.Action("Index", "Preview" , new { area="OrchardCore.Templates" })"></div>
<div id="renderPreviewUrl" style="display:none" data-value="@Url.Action("Render", "Preview" , new { area="OrchardCore.Templates" })"></div>
<div id="contentPreviewUrl" style="display:none" data-value="@Url.Content("~/")"></div>

<resources type="Footer" />

<script>
    var indexPreviewUrl = $(document.getElementById('indexPreviewUrl')).data('value');
    var renderPreviewUrl = $(document.getElementById('renderPreviewUrl')).data('value');
    var contentPreviewUrl = $(document.getElementById('contentPreviewUrl')).data('value');
    var iframe = document.getElementById('iframe');
    var previewEventTimer = null;
    var previewRenderTimer = null;
    var previewRendering;
    var previewRenderData;
    var initialized;

    $(function () {
        $(window).on('storage', function (ev) {
            if (ev.key == 'OrchardCore.templates:not-connected') {
                $(notConnectedWarning).show();
            }
            else if (ev.key == 'OrchardCore.templates') {
                if (ev.originalEvent.newValue != null) {
                    // Smooth event cascading
                    clearTimeout(previewEventTimer);
                    previewEventTimer = setTimeout(function () { renderPreview(ev.originalEvent.newValue); }, 150);
                    $(notConnectedWarning).hide();
                }
            }
        });

        // override default behavior of Bootstrap's. We only hide, not remove the alert.
        $('#close-warning').on('click', function () {
            $('#notConnectedWarning').hide();
        });

        $('#close-server-warning').on('click', function () {
            $('#serverErrorWarning').hide();
        });

        var preview = localStorage.getItem('OrchardCore.templates');

        if (preview == null) {
            // notify the editor to render the preview
            localStorage.setItem('OrchardCore.templates:ready', '');
            localStorage.removeItem('OrchardCore.templates:ready');
        }
        else {
            renderPreview(preview);
        }
    });

    iframe.onload = function () {
        // The iframe may not be well setup after the first loading and then on the first editor update
        // we may lose the scrolling position. A workaround is to refrech the page once after or to add
        // here a delay that really block the thread before exiting. Here, we just rewrite the document.
        if (!initialized) {
            if (this.contentWindow) {
                iframe.contentWindow.document.open();
                iframe.contentWindow.document.write(previewRenderData);
                iframe.contentWindow.document.close();
            }
            initialized = true;
        }
        previewRendering = false;

        if (this.contentWindow && this.contentWindow.location.pathname != indexPreviewUrl) {
            contentPreviewUrl = this.contentWindow.location.pathname;
        }
    }

    function renderPreview(value) {
        if (previewRendering) {
            // Defer the last rendering
            clearTimeout(previewRenderTimer);
            previewRenderTimer = setTimeout(function () { renderPreview(value); }, 100);
        }

        previewRendering = true;
        clearTimeout(previewRenderTimer);

        try {
            var formData = JSON.parse(value);
            if (!formData) {
                previewRendering = false;
                return;
            }
            formData += '&' + $.param({ 'Handle': contentPreviewUrl || "" });

            $.post(renderPreviewUrl, formData)
                .done(function (data) {
                    if (iframe && iframe.contentWindow) {
                        iframe.contentWindow.document.open();
                        iframe.contentWindow.document.write(data);
                        iframe.contentWindow.document.close();
                        previewRenderData = data;
                    }
                    $(serverErrorWarning).hide();
                })
                .fail(function (data) {
                    if (data.status) {
                        var ul = $('#serverErrorWarning ul').empty();
                        var error = 'Status code ' + data.status;
                        console.error(error);
                        $('<li />').text(error).appendTo(ul);
                        $(serverErrorWarning).show();
                    }
                    previewRendering = false;
                });
        }
        catch (e) {
            previewRendering = false;
            console.log('Error while previewing: ' + e);
        }
    }
</script>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Templates/Views/Preview/Render.cshtml
@await DisplayAsync(Model)

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Templates/Views/Preview/_Layout.cshtml
<!DOCTYPE html>
<html lang="@Orchard.CultureName()">
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>@RenderTitleSegments(Site.SiteName, "before")</title>
  </head>
  <body dir="@Orchard.CultureDir()">
      @RenderBody()
  </body>
</html>