Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ItemController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Display;
using OrchardCore.DisplayManagement.ModelBinding;

namespace OrchardCore.Contents.Controllers
{
    public class ItemController : Controller
    {
        private readonly IContentManager _contentManager;
        private readonly IContentItemDisplayManager _contentItemDisplayManager;
        private readonly IAuthorizationService _authorizationService;
        private readonly IUpdateModelAccessor _updateModelAccessor;

        public ItemController(
            IContentManager contentManager,
            IContentItemDisplayManager contentItemDisplayManager,
            IAuthorizationService authorizationService,
            IUpdateModelAccessor updateModelAccessor)
        {
            _authorizationService = authorizationService;
            _contentItemDisplayManager = contentItemDisplayManager;
            _contentManager = contentManager;
            _updateModelAccessor = updateModelAccessor;
        }

        public async Task<IActionResult> Display(string contentItemId, string jsonPath)
        {
            var contentItem = await _contentManager.GetAsync(contentItemId, jsonPath);

            if (contentItem == null)
            {
                return NotFound();
            }

            if (!await _authorizationService.AuthorizeAsync(User, CommonPermissions.ViewContent, contentItem))
            {
                return this.ChallengeOrForbid();
            }

            var model = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, _updateModelAccessor.ModelUpdater);

            return View(model);
        }

        public async Task<IActionResult> Preview(string contentItemId)
        {
            if (contentItemId == null)
            {
                return NotFound();
            }

            var versionOptions = VersionOptions.Latest;

            var contentItem = await _contentManager.GetAsync(contentItemId, versionOptions);

            if (contentItem == null)
            {
                return NotFound();
            }

            if (!await _authorizationService.AuthorizeAsync(User, CommonPermissions.PreviewContent, contentItem))
            {
                return this.ChallengeOrForbid();
            }

            var model = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, _updateModelAccessor.ModelUpdater);

            return View(model);
        }
    }
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/ViewComponents/SelectContentTypesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement.Metadata;
using OrchardCore.ContentManagement.Metadata.Models;
using OrchardCore.Contents.ViewModels;

namespace OrchardCore.Contents.ViewComponents
{
    public class SelectContentTypesViewComponent : ViewComponent
    {
        private readonly IContentDefinitionManager _contentDefinitionManager;

        public SelectContentTypesViewComponent(IContentDefinitionManager contentDefinitionManager)
        {
            _contentDefinitionManager = contentDefinitionManager;
        }

        public IViewComponentResult Invoke(IEnumerable<string> selectedContentTypes, string htmlName, string stereotype)
        {
            if (selectedContentTypes == null)
            {
                selectedContentTypes = Array.Empty<string>();
            }

            var contentTypes = ContentTypeSelection.Build(_contentDefinitionManager, selectedContentTypes);

            if (!String.IsNullOrEmpty(stereotype))
            {
                contentTypes = contentTypes
                    .Where(x => x.ContentTypeDefinition.GetStereotype() == stereotype)
                    .ToArray();
            }

            var model = new SelectContentTypesViewModel
            {
                HtmlName = htmlName,
                ContentTypeSelections = contentTypes
            };

            return View(model);
        }
    }
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/AuditTrailContentEventDiff.DetailAdmin.cshtml
@model AuditTrailContentEventDetailViewModel

@{
    var contentEvent = Model.ContentEvent;
    var contentItem = contentEvent.ContentItem;
    var versionNumber = contentEvent.VersionNumber;
    var latestVersionId = Model.LatestVersionId;
    var newTime = await DisplayAsync(await New.Timespan(Utc: Model.AuditTrailEvent.CreatedUtc, Format: "g"));
    var newText = contentItem.DisplayText;
    var oldTime = await DisplayAsync(await New.Timespan(Utc: Model.PreviousContentItem?.ModifiedUtc, Format: "g"));
    var oldText = Model.PreviousContentItem?.DisplayText;
}

<style asp-name="audittrailui" asp-src="~/OrchardCore.AuditTrail/Styles/audittrailui.min.css" debug-src="~/OrchardCore.AuditTrail/Styles/audittrailui.css" at="Head" depends-on="admin"></style>

@if (Model.PreviousContentItem != null)
{
    <script asp-name="jsdiff" depends-on="jQuery" asp-src="~/OrchardCore.AuditTrail/Scripts/diff.min.js" debug-src="~/OrchardCore.AuditTrail/Scripts/diff.js" cdn-src="https://cdnjs.cloudflare.com/ajax/libs/jsdiff/4.0.2/diff.min.js" debug-cdn-src="https://cdnjs.cloudflare.com/ajax/libs/jsdiff/4.0.2/diff.js" version="4.0.2" at="Foot"></script>
    <script at="Foot" asp-name="prism" depends-on="jsdiff" asp-src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js"></script>
    <script at="Foot" asp-name="prismjson" depends-on="prism" asp-src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-json.min.js"></script>
    <script at="Foot" asp-name="diffviewer" depends-on="prismjson" asp-src="~/OrchardCore.AuditTrail/Scripts/diffviewer.js"></script>
    <div id="diffapp" data-split="@T["Split"]" data-unified="@T["Unified"]" data-old="@Model.Previous" data-new="@Model.Current" data-old-time="@oldTime" data-old-text="@oldText" data-new-time="@newTime" data-new-text="@newText"></div>
}
else
{
    <p class="alert alert-info">@T["No previous content item available to diff against"]</p>
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentItemDeploymentStep.Fields.Thumbnail.cshtml
@model ShapeViewModel<ContentItemDeploymentStep>

<h4 class="card-title">@T["Content Item"]</h4>
<p>@T["Exports a specified content item."]</p>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentPublishedEvent.Fields.Edit.cshtml
@using OrchardCore.Contents.Workflows.ViewModels
@model ContentPublishedEventViewModel

<div class="mb-3" asp-validation-class-for="SelectedContentTypeNames">
    <label asp-for="SelectedContentTypeNames">@T["Content Types"]</label>
    @await Component.InvokeAsync("SelectContentTypes", new { selectedContentTypes = Model.SelectedContentTypeNames, htmlName = Html.NameFor(m => m.SelectedContentTypeNames) })
    <span asp-validation-for="SelectedContentTypeNames"></span>
    <span class="hint">@T["Select any content types to filter on."]</span>
</div>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentPublishedEvent.Fields.Thumbnail.cshtml
<h4 class="card-title"><i class="fa fa-bolt" aria-hidden="true"></i>@T["Content Published"]</h4>
<p>@T["Content is published."]</p>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentTypesSitemapSource.Thumbnail.cshtml
@model ShapeViewModel<ContentTypesSitemapSource>

<h4 class="card-title">@T["Sitemap Content Types"]</h4>
<p>@T["Add sitemap entries for each one of the selected content types."]</p>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentVersionedEvent.Fields.Thumbnail.cshtml
<h4 class="card-title"><i class="fa fa-bolt" aria-hidden="true"></i>@T["Content Versioned"]</h4>
<p>@T["Content is versioned."]</p>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-ContentType.Thumbnail.cshtml
@model ShapeViewModel<ContentOptionsViewModel>
@{
    var term = Model.Value.FilterResult.FirstOrDefault(x => x.TermName == "type");
}

<h4 class="card-title">Content Type</h4>
<pre class="mb-3">@(@term != null ? @term.ToString() : "type:...")</pre>
<p>@T["Filters on a specified content type."]</p>
<div class="d-block text-end">
    <span>
        <i class="fas fa-sm fa-minus text-primary" aria-hidden="true"></i>
    </span>
</div>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentsAdminFilters-Sort.Thumbnail.cshtml
@model ShapeViewModel<ContentOptionsViewModel>
@{
    var term = Model.Value.FilterResult.FirstOrDefault(x => x.TermName == "sort");
}

<h4 class="card-title">Sort</h4>
<pre class="mb-3">@(@term != null ? @term.ToString() : "sort:...")</pre>
<p>@T["Orders by a content item value."]</p>
<div class="d-block text-end">
    <span>
        <i class="fas fa-sm fa-minus text-primary" aria-hidden="true"></i>
    </span>
</div>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/CreateContentTask.Fields.Edit.cshtml
@using OrchardCore.Contents.Workflows.ViewModels
@model CreateContentTaskViewModel

<div class="mb-3" asp-validation-class-for="ContentType">
    <label asp-for="ContentType">@T["Content Type"]</label>
    <select asp-for="ContentType" asp-items="@Model.AvailableContentTypes" class="form-select" asp-validation-class-for="ContentType"></select>
    <span asp-validation-for="ContentType"></span>
    <span class="hint">@T["Select the type of content to create."]</span>
</div>

<div class="mb-3" asp-validation-class-for="Publish">
    <div class="form-check">
        <input type="checkbox" class="form-check-input" asp-for="Publish" />
        <label class="form-check-label" asp-for="Publish">@T["Publish"]</label>
        <span class="hint dashed">@T["Check if you want the content item to be published when being created. Leave unchecked to create a draft version."]</span>
    </div>
</div>

<div class="mb-3" asp-validation-class-for="ContentProperties">
    <label asp-for="ContentProperties">@T["Content Properties"]</label>
    <textarea asp-for="ContentProperties" class="form-control"></textarea>
    <span asp-validation-for="ContentProperties"></span>
    <span class="hint">@T["Optionally provide values for the content parts, fields and their properties in JSON format. With Liquid support."]</span>
</div>

<style asp-name="codemirror"></style>
<script asp-name="codemirror" depends-on="admin" at="Foot"></script>
<script asp-name="codemirror-mode-javascript" at="Foot"></script>
<script asp-name="codemirror-addon-display-autorefresh" at="Foot"></script>
<script asp-name="codemirror-addon-mode-simple" at="Foot"></script>
<script asp-name="codemirror-addon-mode-multiplex" at="Foot"></script>
<script asp-name="codemirror-mode-xml" at="Foot"></script>
<script asp-src="~/OrchardCore.Liquid/codemirror/liquid.js" at="Foot"></script>

<script at="Foot">
$(function () {
    var editor = CodeMirror.fromTextArea(document.getElementById('@Html.IdFor(x => x.ContentProperties)'), {
        autoRefresh: true,
        lineNumbers: true,
        styleActiveLine: true,
        matchBrackets: true,
        mode: { name: "liquid" },
      });
});
</script>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/DeleteContentTask.Fields.Design.cshtml
@model ContentTaskViewModel<DeleteContentTask>

<header>
    <h4><i class="fa fa-trash" aria-hidden="true"></i>@Model.Activity.GetTitleOrDefault(() => T["Delete Content"])</h4>
</header>
@if (string.IsNullOrWhiteSpace(Model.Activity.Content?.Expression))
{
    <span>@T["Delete content provided via the <em>ContentItem</em> input argument"]</span>
}
else
{
    <span>@T["Delete content using expression: <em>{0}</em>", Model.Activity.Content.Expression]</span>
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/PublishContentTask.Fields.Thumbnail.cshtml
<h4 class="card-title"><i class="fa fa-cloud-upload" aria-hidden="true"></i>@T["Publish Content"]</h4>
<p>@T["Publish a content item."]</p>

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/RetrieveContentTask.Fields.Design.cshtml
@model ContentTaskViewModel<RetrieveContentTask>

<header>
    <h4><i class="fa fa-search" aria-hidden="true"></i>@Model.Activity.GetTitleOrDefault(() => T["Retrieve Content"])</h4>
</header>

@if (string.IsNullOrWhiteSpace(Model.Activity.Content?.Expression))
{
    <span>@T["Retrieve content provided via the <em>ContentItemId</em> input argument"]</span>
}
else
{
    <span>@T["Retrieve content using expression: <em>{0}</em>", Model.Activity.Content.Expression]</span>
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/UnpublishContentTask.Fields.Design.cshtml
@model ContentTaskViewModel<UnpublishContentTask>

<header>
    <h4><i class="fa fa-cloud-download" aria-hidden="true"></i>@Model.Activity.GetTitleOrDefault(() => T["Unpublish Content"])</h4>
</header>

@if (string.IsNullOrWhiteSpace(Model.Activity.Content?.Expression))
{
    <span>@T["Unpublish content provided via the <em>ContentItem</em> input argument"]</span>
}
else
{
    <span>@T["Unpublish content using expression: <em>{0}</em>", Model.Activity.Content.Expression]</span>
}

Benchmark_Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/UnpublishContentTask.Fields.Edit.cshtml
@using OrchardCore.Contents.Workflows.ViewModels
@model UnpublishContentTaskViewModel

<div class="mb-3" asp-validation-class-for="Expression">
    <label asp-for="Expression">@T["Expression"]</label>
    <input type="text" asp-for="Expression" class="form-control code" autofocus />
    <span asp-validation-for="Expression"></span>
    <span class="hint">@T["Enter a JavaScript expression that evaluates to the content item (or its 'ContentItemId') to be unpublished. For example: input(\"ContentItem\"). If no expression is specified, the workflow's \"ContentItem\" input variable or \"ContentItem\" property will be used."]</span>
</div>